---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mesosphere.github.io-dkp-insights-charts-attached
  namespace: ${workspaceNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: supported
spec:
  url: "${helmMirrorURL:=http://mesosphere.github.io/dkp-insights-charts-attached}"
  interval: 10m
