---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dkp-insights-kubernetes-charts.banzaicloud.com
  namespace: ${workspaceNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: supported
spec:
  url: "${helmMirrorURL:=https://kubernetes-charts.banzaicloud.com}"
  interval: 10m
